name: CVE Scanning for Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'pyproject.toml'
      - 'safety-policy.yml'
      - '.github/workflows/cve-scanning-python.yml'

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  scan:
    name: Build and test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install package and dependencies
        run: pip install .[dev]
      - name: Freeze installed dependencies
        run: pip freeze > requirements.txt
      - name: Install safety
        run: pip install safety
      - name: Scan CVEs
        env:
          SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
        run: safety check -r requirements.txt --full-report --policy-file safety-policy.yml
        working-directory: .
